In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report
import keras
from keras.layers import Dense
from keras.models import Sequential
dataset = pd.read_csv('iris.csv',names=['sep_l','sep_w','pet_l','pet_w','label'])
dataset

sep_l  sep_w  pet_l  pet_w           label
0      5.1    3.5    1.4    0.2     Iris-setosa
1      4.9    3.0    1.4    0.2     Iris-setosa
2      4.7    3.2    1.3    0.2     Iris-setosa
3      4.6    3.1    1.5    0.2     Iris-setosa
4      5.0    3.6    1.4    0.2     Iris-setosa
..     ...    ...    ...    ...             ...
145    6.7    3.0    5.2    2.3  Iris-virginica
146    6.3    2.5    5.0    1.9  Iris-virginica
147    6.5    3.0    5.2    2.0  Iris-virginica
148    6.2    3.4    5.4    2.3  Iris-virginica
149    5.9    3.0    5.1    1.8  Iris-virginica

[150 rows x 5 columns]

In [2]:
X = dataset.iloc[:,0:4].values
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [3]:
y = dataset.iloc[:,4].values
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [4]:
#example 1 for LabelEncoder
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() 
y = le.fit_transform(y)
#to map or transform data 

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)
X_train.shape

(120, 4)

In [7]:
X_test.shape

(30, 4)

In [8]:
#one type of syntax
model = Sequential([
    Dense(10,activation="relu",input_shape=[4]),
    Dense(10,activation="relu"),
    Dense(3,activation="softmax")])

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                50        
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 33        
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________


In [10]:
#parse cross because of label_endoder is used
model.compile(loss="sparse_categorical_crossentropy",optimizer='sgd',metrics=['accuracy'])
model.fit(X_train,y_train,epochs=100)

Epoch 1/100
4/4 [==============================] - 0s 5ms/step - loss: 3.0462 - accuracy: 0.3667
Epoch 2/100
4/4 [==============================] - 0s 4ms/step - loss: 1.6125 - accuracy: 0.3667
Epoch 3/100
4/4 [==============================] - 0s 3ms/step - loss: 1.1746 - accuracy: 0.3667
Epoch 4/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0353 - accuracy: 0.3667
Epoch 5/100
4/4 [==============================] - 0s 2ms/step - loss: 0.9771 - accuracy: 0.3667
Epoch 6/100
4/4 [==============================] - 0s 2ms/step - loss: 0.9488 - accuracy: 0.3667
Epoch 7/100
4/4 [==============================] - 0s 3ms/step - loss: 0.9280 - accuracy: 0.3667
Epoch 8/100
4/4 [==============================] - 0s 3ms/step - loss: 0.9147 - accuracy: 0.3667
Epoch 9/100
4/4 [==============================] - 0s 3ms/step - loss: 0.9077 - accuracy: 0.3833
Epoch 10/100
4/4 [==============================] - 0s 3ms/step - loss: 0.8961 - accuracy: 0.5000
Epoch 11/100
4/4 [===========

4/4 [==============================] - 0s 2ms/step - loss: 0.5044 - accuracy: 0.6917
Epoch 85/100
4/4 [==============================] - 0s 2ms/step - loss: 0.4983 - accuracy: 0.6917
Epoch 86/100
4/4 [==============================] - 0s 2ms/step - loss: 0.4957 - accuracy: 0.6917
Epoch 87/100
4/4 [==============================] - 0s 2ms/step - loss: 0.4936 - accuracy: 0.6917
Epoch 88/100
4/4 [==============================] - 0s 2ms/step - loss: 0.4931 - accuracy: 0.6917
Epoch 89/100
4/4 [==============================] - 0s 2ms/step - loss: 0.4920 - accuracy: 0.6917
Epoch 90/100
4/4 [==============================] - 0s 2ms/step - loss: 0.4892 - accuracy: 0.6917
Epoch 91/100
4/4 [==============================] - 0s 2ms/step - loss: 0.4882 - accuracy: 0.6917
Epoch 92/100
4/4 [==============================] - 0s 2ms/step - loss: 0.4889 - accuracy: 0.6917
Epoch 93/100
4/4 [==============================] - 0s 2ms/step - loss: 0.4818 - accuracy: 0.6917
Epoch 94/100
4/4 [===============

In [11]:
model.evaluate(X_test,y_test)

1/1 [==============================] - 0s 144ms/step - loss: 0.5043 - accuracy: 0.5667


[0.5043214559555054, 0.5666666626930237]

In [12]:
y_pred = model.predict(X_test)
y_pred.round()

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [13]:
#map data or parse in 1 digit
y_pred = np.argmax(y_pred,axis=1)
y_pred

array([2, 2, 0, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 0, 2, 2,
       0, 0, 2, 0, 0, 2, 2, 0], dtype=int64)

In [14]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

In [15]:
print(confusion_matrix(y_test,y_pred))

[[11  0  0]
 [ 0  0 13]
 [ 0  0  6]]


In [16]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.00      0.00      0.00        13
           2       0.32      1.00      0.48         6

    accuracy                           0.57        30
   macro avg       0.44      0.67      0.49        30
weighted avg       0.43      0.57      0.46        30



C:\Users\Marketing\anaconda3\envs\deepl2\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Marketing\anaconda3\envs\deepl2\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Marketing\anaconda3\envs\deepl2\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [20]:
X1 = dataset.iloc[:,0:4].values
y1 = dataset.iloc[:,[4]].values
#store y data in array for OneHotEncoder
y1

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-se

In [21]:
#example 2 for OneHotEncoder
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)
y1 = ohe.fit_transform(y1)
y1

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [22]:
X1_train,X1_test,y1_train,y1_test = train_test_split(X1,y1,test_size=0.2,random_state=0)

In [23]:
#2nd type of syntax
model1 = Sequential()
model1.add(Dense(10,activation="relu",input_dim=4))
model1.add(Dense(10,activation="relu"))
model1.add(Dense(3,activation="softmax"))

In [24]:
model1.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 10)                50        
_________________________________________________________________
dense_4 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 33        
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________


In [25]:
model1.compile(loss="categorical_crossentropy",optimizer='sgd',metrics=['accuracy'])

In [26]:
model1.fit(X1_train,y1_train,epochs=100)

Epoch 1/100
4/4 [==============================] - 1s 7ms/step - loss: 1.1223 - accuracy: 0.1500
Epoch 2/100
4/4 [==============================] - 0s 2ms/step - loss: 1.0803 - accuracy: 0.3500
Epoch 3/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0337 - accuracy: 0.3667
Epoch 4/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0269 - accuracy: 0.3667
Epoch 5/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0168 - accuracy: 0.3667
Epoch 6/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0068 - accuracy: 0.3667
Epoch 7/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0007 - accuracy: 0.3667
Epoch 8/100
4/4 [==============================] - 0s 3ms/step - loss: 0.9924 - accuracy: 0.3667
Epoch 9/100
4/4 [==============================] - 0s 3ms/step - loss: 0.9844 - accuracy: 0.3667
Epoch 10/100
4/4 [==============================] - 0s 3ms/step - loss: 0.9780 - accuracy: 0.3667
Epoch 11/100
4/4 [===========

4/4 [==============================] - 0s 3ms/step - loss: 0.4800 - accuracy: 0.7167
Epoch 85/100
4/4 [==============================] - 0s 3ms/step - loss: 0.4737 - accuracy: 0.7167
Epoch 86/100
4/4 [==============================] - 0s 2ms/step - loss: 0.4695 - accuracy: 0.8333
Epoch 87/100
4/4 [==============================] - 0s 4ms/step - loss: 0.4651 - accuracy: 0.7000
Epoch 88/100
4/4 [==============================] - 0s 4ms/step - loss: 0.4682 - accuracy: 0.7083
Epoch 89/100
4/4 [==============================] - 0s 3ms/step - loss: 0.4731 - accuracy: 0.7417
Epoch 90/100
4/4 [==============================] - 0s 3ms/step - loss: 0.4555 - accuracy: 0.8667
Epoch 91/100
4/4 [==============================] - 0s 3ms/step - loss: 0.4509 - accuracy: 0.7500
Epoch 92/100
4/4 [==============================] - 0s 3ms/step - loss: 0.4502 - accuracy: 0.7750
Epoch 93/100
4/4 [==============================] - 0s 3ms/step - loss: 0.4466 - accuracy: 0.7583
Epoch 94/100
4/4 [===============

In [27]:
model1.evaluate(X1_test,y1_test)

1/1 [==============================] - 0s 128ms/step - loss: 0.4639 - accuracy: 0.6333


[0.46394264698028564, 0.6333333253860474]

In [32]:
y1_pred = model1.predict(X1_test)
y1_pred.round()

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [33]:
y1_test = np.argmax(y1_test,axis=1)
y1_pred = np.argmax(y1_pred,axis=1)

In [34]:
y1_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0], dtype=int64)

In [35]:
y1_pred

array([2, 2, 0, 2, 0, 2, 0, 2, 2, 1, 2, 2, 2, 2, 2, 0, 2, 2, 0, 0, 2, 2,
       0, 0, 2, 0, 0, 2, 1, 0], dtype=int64)

In [36]:
print(confusion_matrix(y1_test,y1_pred))

[[11  0  0]
 [ 0  2 11]
 [ 0  0  6]]


In [37]:
print(classification_report(y1_test,y1_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.15      0.27        13
           2       0.35      1.00      0.52         6

    accuracy                           0.63        30
   macro avg       0.78      0.72      0.60        30
weighted avg       0.87      0.63      0.59        30

